source 'https://rubygems.org'

# Specify your gem's dependencies in hikkoshi-hexo.gemspec
gemspec

gem "hikkoshi", :path => '../hikkoshi', :group => :development
gem "hikkoshi-jekyll", :path => '../hikkoshi-jekyll', :group => :development
